import Header from "@/components/app/Header";
import "./globals.css";
import Footer from "@/components/app/Footer";

export const metadata = {
  title: "Proxy Lab App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/images/favicon.svg" sizes="any" />
      </head>
      <body>
        <Header />
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
